--------------------------------------------------------
--  Fichier créé - lundi-février-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "GHADA"."FOURNISSEURS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATE_DEB" VARCHAR2(20 BYTE), 
	"DATE_FIN" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GHADA.FOURNISSEURS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHADA"."FOURNISSEURS_PK" ON "GHADA"."FOURNISSEURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "GHADA"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHADA"."FOURNISSEURS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "GHADA"."FOURNISSEURS" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "GHADA"."FOURNISSEURS" MODIFY ("DATE_DEB" NOT NULL ENABLE);
  ALTER TABLE "GHADA"."FOURNISSEURS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "GHADA"."FOURNISSEURS" MODIFY ("ID" NOT NULL ENABLE);
